#!/bin/csh
#
# DART software - Copyright UCAR. This open source software is provided
# by UCAR, "as is", without charge, subject to all terms of use at
# http://www.image.ucar.edu/DAReS/DART/DART_download
#
# usage: mkmf_bias_corr [ -mpi | -nompi ]
#
# without any args (or with -nompi), builds without mpi libraries, and it will run
# as a serial executable. if -mpi is given, it will be compiled with the mpi
# libraries and can run with multiple cooperating processes.

if ( $#argv > 0 ) then
  if ("$argv[1]" == "-mpi") then
    setenv usingmpi 1
  else if ("$argv[1]" == "-nompi") then
    setenv usingmpi 0
  else
    echo "Unrecognized argument to mkmf_bias_corr: $argv[1]"
    echo "Usage: mkmf_bias_corr [ -mpi | -nompi ]"
    echo " default is to generate a Makefile without MPI support."
    exit -1
  endif
else
  setenv usingmpi 0
endif

# make a backup copy of the path_names file, and then use
# sed to make sure it includes either the non-mpi subroutines,
# or the subroutines which really call mpi.

set pathFile = path_names_bias_corr

cp -f ${pathFile} ${pathFile}.back

if ( $usingmpi ) then

  echo "Makefile uses MPI version of code."
  sed -e 's;/bias_corr;/bias_corr;' ${pathFile}.back >! ${pathFile}
  setenv wrapper_arg -w
  set EXENAME = bias_corr.exe

else

  echo "Makefile uses serial version of code."
  sed -e 's;/bias_corr;/bias_corr;' ${pathFile}.back >! ${pathFile}
  setenv wrapper_arg ""
  set EXENAME = bias_corr.exe

endif

# remove temp file and now really call mkmf to generate makefile
rm -f ${pathFile}.back

    ../../../../../build_templates/mkmf -p ${EXENAME} \
-t  ../../../../../build_templates/mkmf.template \
-a "../../../../.." ${wrapper_arg} ${pathFile}

exit $status

